#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Overview
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Overview/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Overview\Index.cshtml"
  
    ViewBag.Title = "overview";

            
            #line default
            #line hidden
WriteLiteral(@"

<h2><span>objective</span></h2>
<p>To apply and grow my existing skillset in a challenging, fast-paced, and rewarding software engineering environment.</p>
<p>To bring a new level of efficiency and stability to software projects by utilizing the latest technologies and software engineering ideals.</p>

<h2><span>summary</span></h2>
<p>Highly skilled software engineer who prides himself on completing tasks on time while maintaining high quality standards and adhering to software development best practices.</p>
<ul>
    <li>Plan, research, estimate and develop solutions for Government contracts.</li>
    <li>Responsible for architecting and developing sophisticated SOAP and RESTful API (HealthIndicators.gov).</li>
    <li>Make and implement high-level decisions regarding overall application architecture, use and design.</li>
    <li>Design and develop entire SQL Server databases; inspect queries and apply performance updates as needed.</li>
    <li>Constantly learning new technologies, frameworks and tools.</li>
</ul>
");

        }
    }
}
#pragma warning restore 1591
