#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.SkillsAndTech
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SkillsAndTech/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\SkillsAndTech\Index.cshtml"
  
    ViewBag.Title = "skills & tech";

            
            #line default
            #line hidden
WriteLiteral(@"

<h2><span>skills</span></h2>
<ul>
    <li>Bottom-up database design and development.</li>
    <li>Project & feature design and development.</li>
    <li>UI design and implementation.</li>
    <li>Clean, organized, efficient, reusable code.</li>
</ul>

<h2><span>technology</span></h2>
<ul>
    <li>.NET, C#, ASP.NET MVC, ASP.NET WebForms, Ruby on Rails, PHP, Java, Hibernate, Spring, Struts</li>
    <li>HTML 5, CSS 3, JavaScript, jQuery, Bootstrap, Knockout, Highcharts/Highmaps</li>
    <li>Visual Studio, Eclipse, NetBeans</li>
    <li>IIS, Apache, Nginx, Tomcat, Weblogic</li>
    <li>SQL Server, MySQL, Oracle</li>
    <li>Windows, Linux</li>
    <li>Networking, DNS, server management (Windows, Linux, Amazon Web Services)</li>
</ul>

<h2><span>hobbies</span></h2>
<ul>
    <li>Keeping up with the latest in software development.</li>
    <li>3D printing – QuantumConcepts on Thingiverse.com.</li>
    <li>General DIY and learning how things work.</li>
    <li>Technology, astronomy, travel, photography.</li>
</ul>");

        }
    }
}
#pragma warning restore 1591
