#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Overview
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Overview/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Overview\Index.cshtml"
  
    ViewBag.Title = "overview";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<section>\r\n");

            
            #line 6 "..\..\Views\Overview\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Overview\Index.cshtml"
      Html.RenderPartial("_Content");
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"subsection\"");

WriteLiteral(">\r\n        <h2><span>projects</span></h2>\r\n        <p>Please find below a small c" +
"ollection of my work. I\'ve highlighted my involvement on each project.</p>\r\n    " +
"    <ul");

WriteLiteral(" class=\"blocks\"");

WriteLiteral(">\r\n            <li>\r\n                <h3>Health Indicators Warehouse <text");

WriteLiteral(" class=\"\"");

WriteLiteral(">(HIW)</text><a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://healthindicators.gov\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Data Warehouse of health-related indicators - CDC/NCHS.</div>\r\n                <" +
"div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                    <p>The HIW contains data from 125+ sources across 1,200+ h" +
"ealth indicators. This project is part of the <a");

WriteLiteral(" href=\"http://www.data.gov\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Data.gov</a>\'s <a");

WriteLiteral(" href=\"http://www.whitehouse.gov/open\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Open Data Initiative</a> and exposes massive amounts of publicly-consumable heal" +
"th-related data.</p>\r\n                </div>\r\n                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"cs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mssql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"html\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"css\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"js\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n\r\n            <li>\r\n           " +
"     <h3>HIW Developers &amp; Services<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://developers.healthindicators.gov\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Over 1,000 RESTful (and SOAP) service methods.</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>Exposes data from the HIW. Custom CodeGenerator templates were used to generate the service methods and documentation. The system includes a real-time URL builder/service tester and API key registration/verification.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"cs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mssql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"html5\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"css3\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"bs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"js\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ko\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n\r\n            <li>\r\n           " +
"     <h3>CodeGenerator<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://quantumconceptscorp.com/Products/CodeGenerator.aspx\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Develop stable, robust and highly versatile software, faster!</div>\r\n           " +
"     <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>This tool allows you and your team to get the nuts and bolts of any project up and running amazingly fast. The backbone of CodeGenerator relies on technologies that your team probably already knows - XML and XSLT. You design an XSL Template once and CodeGenerator handles the rest.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"cs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"winforms\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mssql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mysql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n\r\n            <li>\r\n           " +
"     <h3>Platform Liberty</h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Empowering candidates in the fight for liberty.</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>The goal of this project is to provide an inexpensive, easy-to-use web application for liberty candidates. This platform will be available to any candidate who is on the side of liberty - regardless of party their party affiliation. 10+ instances.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"rails\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mysql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"html5\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"css3\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"bs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"js\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ko\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n\r\n            <li>\r\n           " +
"     <h3>Carson for Congress<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://jeffreycarson.platformliberty.org\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Restoring Sanity</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                    <p>Built atop Platform Liberty and customized to fit the n" +
"eeds of Jeffrey Carson\'s 2014 Congressional campaign.</p>\r\n                </div" +
">\r\n                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"rails\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mysql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"html5\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"css3\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"bs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"js\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ko\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n\r\n            <li>\r\n           " +
"     <h3>AeroBazaar<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://aerobazaar.com\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">The most beautiful place to buy and sell aircraft online.</div>\r\n               " +
" <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>A robust aircraft listing engine allows potential aircraft buyers to easily find what they're looking for. Sellers can manage their inventory and add detailed information for each of their aircraft.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"php\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"mysql\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"html5\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"css3\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"bs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"js\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ko\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n\r\n            <li>\r\n           " +
"     <h3>7Flix<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://quantumconceptscorp.com/Products/7Flix.aspx\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">A full-featured Netflix client for Windows Phones.</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>Although this app is no longer available, since Netflix ditched their public API, it was the most complete Netflix client on the platform at the time. It included queue management features and the ability to search and browse the entire Netflix library.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tech-items\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"cs\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"wp\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"api\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"sl\"");

WriteLiteral("></li>\r\n                    <li");

WriteLiteral(" class=\"ui-ux\"");

WriteLiteral("></li>\r\n                </ul>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n\r\n  " +
"  <div");

WriteLiteral(" class=\"subsection\"");

WriteLiteral(">\r\n        <h2><span>self-rankings</span></h2>\r\n        <p>I\'ve compiled a list o" +
"f the technologies I work with most often. The relative size of each item indica" +
"tes my level of expertise.</p>\r\n        <ul");

WriteLiteral(" class=\"blocks expertise tech-items\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"cs\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"mvc\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"webforms\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"mssql\"");

WriteLiteral(" data-expertise=\"9\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"mysql\"");

WriteLiteral(" data-expertise=\"7\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"rails\"");

WriteLiteral(" data-expertise=\"6\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"php\"");

WriteLiteral(" data-expertise=\"5\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"wp\"");

WriteLiteral(" data-expertise=\"4\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"winforms\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"html\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"css\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"bs\"");

WriteLiteral(" data-expertise=\"8\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"js\"");

WriteLiteral(" data-expertise=\"10\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"ko\"");

WriteLiteral(" data-expertise=\"7\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"sl\"");

WriteLiteral(" data-expertise=\"4\"");

WriteLiteral("></li>\r\n            ");

WriteLiteral("\r\n        </ul>\r\n    </div>\r\n</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var minSize = 30;\r\n        var maxSize = 100;\r\n        var padding = 4" +
";\r\n        var sizeRange = (maxSize - minSize);\r\n        var movers = [\r\n       " +
"     function ($tag, collidedTags) { $tag.css(\"top\", getExtreme(collidedTags, Ma" +
"th.min, \"top\") - $tag.bounds.height - padding); },   //Up\r\n            function " +
"($tag, collidedTags) { $tag.css(\"left\", getExtreme(collidedTags, Math.max, \"righ" +
"t\") + padding); },                     //Right\r\n            function ($tag, coll" +
"idedTags) { $tag.css(\"top\", getExtreme(collidedTags, Math.max, \"bottom\") + paddi" +
"ng); },                     //Down\r\n            function ($tag, collidedTags) { " +
"$tag.css(\"left\", getExtreme(collidedTags, Math.min, \"left\") - $tag.bounds.width " +
"- padding); }   //Left\r\n        ];\r\n        var centerX, centerY;\r\n\r\n        fun" +
"ction layoutTags($container) {\r\n            var $tags = $container.find(\"li\");\r\n" +
"\r\n            initTags($container, $tags);\r\n            sortTags($container, $ta" +
"gs);\r\n            sizeTags($container, $tags);\r\n            positionTags($contai" +
"ner, $tags);\r\n        }\r\n\r\n        function initTags($container, $tags) {\r\n     " +
"       centerX = ($container.width() / 2);\r\n            centerY = ($container.he" +
"ight() / 2);\r\n            $tags.each(function () { this.expertise = Number(this." +
"getAttribute(\"data-expertise\")); })\r\n        }\r\n\r\n        function sortTags($con" +
"tainer, $tags) {\r\n            $tags.sort(function (a, b) {\r\n                var " +
"aValue = a.expertise;\r\n                var bValue = b.expertise;\r\n\r\n            " +
"    if (aValue > bValue)\r\n                    return -1;\r\n                else i" +
"f (bValue > aValue)\r\n                    return 1;\r\n\r\n                return 0;\r" +
"\n            });\r\n        }\r\n\r\n        function sizeTags($container, $tags) {\r\n " +
"           var values = $tags.map(function () { return this.expertise; });\r\n    " +
"        var min = Math.min.apply(Math, values);\r\n            var max = Math.max." +
"apply(Math, values);\r\n            var range = (max - min);\r\n\r\n            $tags." +
"each(function () {\r\n                var $tag = $(this);\r\n                var val" +
"ue = $tag[0].expertise;\r\n                var relativeValue = ((value - min) / ra" +
"nge);\r\n                var size = (minSize + (relativeValue * sizeRange));\r\n\r\n  " +
"              $tag.width(size);\r\n                $tag.height(size);\r\n           " +
"     $tag.css(\"line-height\", size + \"px\");\r\n            })\r\n        }\r\n\r\n       " +
" function positionTags($container, $tags) {\r\n            var unplacedTags = $.ma" +
"keArray($tags.map(function () { return $(this); }));\r\n            var placedTags" +
" = new Array();\r\n            \r\n            //Place tags in a loop, randomly grab" +
"bing each tag (except for the first iteration, start with the \"largest\" tag).\r\n " +
"           while (unplacedTags.length > 0 && !stopTags) {\r\n                var t" +
"agIndex = (placedTags.length == 0 ? 0 : Math.floor(Math.random() * unplacedTags." +
"length));\r\n                var $tag = unplacedTags.splice(tagIndex, 1)[0];\r\n\r\n  " +
"              //Place the tag.\r\n                placeTag(placedTags, $tag);\r\n\r\n " +
"               //\"Mark\" the tag as placed.\r\n                placedTags.push($tag" +
");\r\n            }\r\n\r\n            //Shift all tags so there are no negative coord" +
"inates.\r\n            shiftTags(placedTags);\r\n            sizeContainer($containe" +
"r, placedTags);\r\n        }\r\n\r\n        function placeTag(placedTags, $tag) {\r\n   " +
"         var collidedTags = null;\r\n            var moverIndex = 0;\r\n\r\n          " +
"  //Start at the center.\r\n            $tag.bounds = new Bounds($tag);\r\n         " +
"   $tag.css(\"left\", (centerX - $tag.bounds.halfWidth));\r\n            $tag.css(\"t" +
"op\", (centerY - $tag.bounds.halfHeight));\r\n            \r\n            do {\r\n     " +
"           //Always clear the collided tag and recalculate the bounds.\r\n        " +
"        collidedTags = new Array();\r\n                $tag.bounds = new Bounds($t" +
"ag);\r\n\r\n                //Find the first collided tag (if any).\r\n               " +
" for (var i = 0; i < placedTags.length; i++)\r\n                    if (placedTags" +
"[i].bounds.collidesWith($tag.bounds))\r\n                        collidedTags.push" +
"(placedTags[i]);\r\n\r\n                //If there\'s a collision, move the tag based" +
" on an Archimedean Spiral.\r\n                if (collidedTags.length > 0) {\r\n    " +
"                movers[moverIndex]($tag, collidedTags);\r\n\r\n                    i" +
"f (moverIndex == (movers.length - 1))\r\n                        return;\r\n        " +
"            else\r\n                        moverIndex = (moverIndex == (movers.le" +
"ngth - 1) ? 0 : moverIndex + 1);\r\n                }\r\n            } while (collid" +
"edTags.length > 0 && !stopTags);\r\n        }\r\n        var stopTags = false;\r\n\r\n  " +
"      function shiftTags($tags) {\r\n            var minX = getExtreme($tags, Math" +
".min, \"left\");\r\n            var minY = getExtreme($tags, Math.min, \"top\");\r\n    " +
"        var moveX = (minX < 0 ? Math.abs(minX) : 0);\r\n            var moveY = (m" +
"inY < 0 ? Math.abs(minY) : 0);\r\n\r\n            if (moveX > 0) {\r\n                " +
"$tags.forEach(function ($tag) {\r\n                    $tag.css(\"left\", $tag.bound" +
"s.left + moveX);\r\n                    $tag.bounds = new Bounds($tag);\r\n         " +
"       });\r\n            }\r\n\r\n            if (moveY > 0) {\r\n                $tags" +
".forEach(function ($tag) {\r\n                    $tag.css(\"top\", $tag.bounds.top " +
"+ moveY);\r\n                    $tag.bounds = new Bounds($tag);\r\n                " +
"});\r\n            }\r\n        }\r\n\r\n        function sizeContainer($container, $tag" +
"s) {\r\n            var maxX = getExtreme($tags, Math.max, \"right\");\r\n            " +
"var maxY = getExtreme($tags, Math.max, \"bottom\");\r\n\r\n            $container.widt" +
"h(maxX);\r\n            $container.height(maxY);\r\n        }\r\n\r\n        function ge" +
"tExtreme(tags, mathFunc, property) {\r\n            return (mathFunc.apply(Math, $" +
".map(tags, function ($tag) { return $tag.bounds[property]; })) || 0);\r\n        }" +
"\r\n\r\n        var Bounds = function Bounds() {\r\n            var Bounds = function " +
"($element) {\r\n                var position = $element.position();\r\n             " +
"   var width = $element.outerWidth();\r\n                var height = $element.out" +
"erHeight();\r\n\r\n                this.left = position.left;\r\n                this." +
"top = position.top;\r\n                this.width = width;\r\n                this.h" +
"eight = height;\r\n                this.right = (position.left + width);\r\n        " +
"        this.bottom = (position.top + height);\r\n                this.halfWidth =" +
" (this.width / 2);\r\n                this.halfHeight = (this.height / 2);\r\n      " +
"          this.center = {\r\n                    x: (this.left + this.halfWidth),\r" +
"\n                    y: (this.top + this.halfHeight)\r\n                };\r\n      " +
"      };\r\n\r\n            Bounds.prototype.collidesWith = function (otherBounds) {" +
"\r\n                return !this.doesNotCollideWith(otherBounds);\r\n            };\r" +
"\n\r\n            Bounds.prototype.doesNotCollideWith = function (otherBounds) {\r\n " +
"               return (this.left > otherBounds.right || this.right < otherBounds" +
".left || this.top > otherBounds.bottom || this.bottom < otherBounds.top);\r\n     " +
"       };\r\n\r\n            return Bounds;\r\n        }();\r\n\r\n        window.scrollTo" +
"(0, document.body.scrollHeight);\r\n        layoutTags($(\"ul.expertise\"));\r\n    </" +
"script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
