#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Overview/Index.cshtml")]
    public partial class _Views_Overview_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Overview_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Overview\Index.cshtml"
  
    ViewBag.Title = "overview";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<section>\r\n");

            
            #line 6 "..\..\Views\Overview\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Overview\Index.cshtml"
      Html.RenderPartial("_Content");
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"subsection\"");

WriteLiteral(">\r\n        <h2><span>projects</span></h2>\r\n        <p>Please find below a small c" +
"ollection of my work. I\'ve highlighted my involvement on each project.</p>\r\n    " +
"    <ul");

WriteLiteral(" class=\"blocks\"");

WriteLiteral(">\r\n            <li>\r\n                <h3>Health Indicators Warehouse <text");

WriteLiteral(" class=\"\"");

WriteLiteral(">(HIW)</text><a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://healthindicators.gov\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Data Warehouse of health-related indicators - CDC/NCHS.</div>\r\n                <" +
"div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                    <p>The HIW contains data from 125+ sources across 1,200+ h" +
"ealth indicators. This project is part of the <a");

WriteLiteral(" href=\"http://www.data.gov\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Data.gov</a>\'s <a");

WriteLiteral(" href=\"http://www.whitehouse.gov/open\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Open Data Initiative</a> and exposes massive amounts of publicly-consumable heal" +
"th-related data.</p>\r\n                </div>\r\n                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"cs mssql html css js uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n\r\n            <li>\r\n                <h3>HIW Developers" +
" &amp; Services<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://developers.healthindicators.gov\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Over 1,000 RESTful (and SOAP) service methods.</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>Exposes data from the HIW. Custom CodeGenerator templates were used to generate the service methods and documentation. The system includes a real-time URL builder/service tester and API key registration/verification.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"cs mssql html5 css3 bs js ko uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n\r\n            <li>\r\n                <h3>CodeGenerator<" +
"a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://quantumconceptscorp.com/Products/CodeGenerator.aspx\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Develop stable, robust and highly versatile software, faster!</div>\r\n           " +
"     <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>This tool allows you and your team to get the nuts and bolts of any project up and running amazingly fast. The backbone of CodeGenerator relies on technologies that your team probably already knows - XML and XSLT. You design an XSL Template once and CodeGenerator handles the rest.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"cs winforms mssql mysql uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n\r\n            <li>\r\n                <h3>Platform Liber" +
"ty</h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Empowering candidates in the fight for liberty.</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>The goal of this project is to provide an inexpensive, easy-to-use web application for liberty candidates. This platform will be available to any candidate who is on the side of liberty - regardless of party their party affiliation. 10+ instances.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"rails mysql html5 css3 bs js ko uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n\r\n            <li>\r\n                <h3>Carson for Con" +
"gress<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://jeffreycarson.platformliberty.org\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">Restoring Sanity</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                    <p>Built atop Platform Liberty and customized to fit the n" +
"eeds of Jeffrey Carson\'s 2014 Congressional campaign.</p>\r\n                </div" +
">\r\n                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"rails mysql html5 css3 bs js ko uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n\r\n            <li>\r\n                <h3>AeroBazaar<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://aerobazaar.com\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">The most beautiful place to buy and sell aircraft online.</div>\r\n               " +
" <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>A robust aircraft listing engine allows potential aircraft buyers to easily find what they're looking for. Sellers can manage their inventory and add detailed information for each of their aircraft.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"php mysql html5 css3 bs js ko uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n\r\n            <li>\r\n                <h3>7Flix<a");

WriteLiteral(" class=\"visit\"");

WriteLiteral(" href=\"http://quantumconceptscorp.com/Products/7Flix.aspx\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a></h3>\r\n                <div");

WriteLiteral(" class=\"tagline\"");

WriteLiteral(">A full-featured Netflix client for Windows Phones.</div>\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <p>Although this app is no longer available, since Netflix ditched their public API, it was the most complete Netflix client on the platform at the time. It included queue management features and the ability to search and browse the entire Netflix library.</p>
                </div>
                <ul");

WriteLiteral(" class=\"features tags\"");

WriteLiteral(" data-tags-keys=\"cs wp api sl uiux\"");

WriteLiteral("></ul>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"subsection\"");

WriteLiteral(">\r\n        <h2><span>self-rankings</span></h2>\r\n        <p>I\'ve compiled a list o" +
"f the technologies I work with most often. The relative size of each item indica" +
"tes my level of expertise.</p>\r\n        <ul");

WriteLiteral(" class=\"blocks expertise\"");

WriteLiteral("></ul>\r\n    </div>\r\n</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5691), Tuple.Create("\"", 5738)
            
            #line 85 "..\..\Views\Overview\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5697), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Scripts/Tags.js")
            
            #line default
            #line hidden
, 5697), false)
);

WriteLiteral("></script>\"\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(\"ul.tags\").tags();\r\n        $(\"ul.expertise\").expertise();\r\n    </sc" +
"ript>\r\n");

});

        }
    }
}
#pragma warning restore 1591
