#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/History.cshtml")]
    public partial class History_ : System.Web.Mvc.WebViewPage<JSM.Web.Models.Shared.Resume.History>
    {
        public History_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h2");

WriteLiteral(" class=\"history-item\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
                          Write(this.Model.DateSpan);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span");

WriteLiteral(" class=\"col-md-6 text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
       Write(this.Model.Organization);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
            
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
             if (!this.Model.OrganizationWebsite.IsNullOrEmpty()) {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" class=\"organization-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 356), Tuple.Create("\"", 394)
            
            #line 10 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
, Tuple.Create(Tuple.Create("", 363), Tuple.Create<System.Object, System.Int32>(this.Model.OrganizationWebsite
            
            #line default
            #line hidden
, 363), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-new-window\"");

WriteLiteral("></span></a>\r\n");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </span>\r\n        <span");

WriteLiteral(" class=\"col-md-3 text-right\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
                                     Write(this.Model.OrganizationLocation);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </span>\r\n</h2>\r\n<h3>");

            
            #line 16 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
Write(this.Model.Role);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\History.cshtml"
  Html.RenderPartial("DisplayTemplates/Content", this.Model.Content);
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
