#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Section.cshtml")]
    public partial class Section_ : System.Web.Mvc.WebViewPage<JSM.Web.Models.Shared.Resume.Section>
    {
        public Section_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteAttribute("class", Tuple.Create(" class=\"", 51), Tuple.Create("\"", 125)
, Tuple.Create(Tuple.Create("", 59), Tuple.Create("section", 59), true)
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Section.cshtml"
, Tuple.Create(Tuple.Create("", 66), Tuple.Create<System.Object, System.Int32>(this.Model.Class.IsNullOrEmpty() ? "" : this.Model.Class
            
            #line default
            #line hidden
, 66), false)
);

WriteLiteral(">\r\n    <h1><span>");

            
            #line 4 "..\..\Views\Shared\DisplayTemplates\Section.cshtml"
         Write(this.Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></h1>\r\n\r\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Section.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Section.cshtml"
      Html.RenderPartial("DisplayTemplates/Content", this.Model.Content);
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
