#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Subsection.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Subsection_cshtml_ : System.Web.Mvc.WebViewPage<JSM.Web.Models.Shared.Resume.Subsection>
    {
        public _Views_Shared_DisplayTemplates_Subsection_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteAttribute("id", Tuple.Create(" id=\"", 54), Tuple.Create("\"", 85)
, Tuple.Create(Tuple.Create("", 59), Tuple.Create("subsection_", 59), true)
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Subsection.cshtml"
, Tuple.Create(Tuple.Create("", 70), Tuple.Create<System.Object, System.Int32>(this.Model.Key
            
            #line default
            #line hidden
, 70), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 86), Tuple.Create("\"", 184)
, Tuple.Create(Tuple.Create("", 94), Tuple.Create("subsection", 94), true)
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Subsection.cshtml"
, Tuple.Create(Tuple.Create("", 104), Tuple.Create<System.Object, System.Int32>(this.Model.Class.IsNullOrEmpty() ? "" : " {0}".FormatString(this.Model.Class)
            
            #line default
            #line hidden
, 104), false)
);

WriteLiteral(">\r\n    <h2><span>");

            
            #line 4 "..\..\Views\Shared\DisplayTemplates\Subsection.cshtml"
         Write(this.Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></h2>\r\n\r\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Subsection.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Subsection.cshtml"
      Html.RenderPartial("DisplayTemplates/Content", this.Model.Content);
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
