#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.WorkHistory
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using JSM.Web.Models.Shared;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/WorkHistory/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\WorkHistory\Index.cshtml"
  
    ViewBag.Title = "work history";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2");

WriteLiteral(" class=\"history-item\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">5/2010 - Present</span>\r\n        <span");

WriteLiteral(" class=\"col-md-6 text-center\"");

WriteLiteral(">Social &amp; Scientific Systems, Inc.</span>\r\n        <span");

WriteLiteral(" class=\"col-md-3 text-right\"");

WriteLiteral(@">Silver Spring, Maryland</span>
    </span>
</h2>
<h3>Senior Software Engineer</h3>
<ul>
    <li>Selected amongst hundreds of employees to attend in-house Leadership Training instructed by the executive team.</li>
    <li>Lead developer for the Health Indicators Warehouse (HealthIndicators.gov) and other government and private applications.</li>
    <li>Senior Developer responsible for system and database design as well as UI design and implementation.</li>
    <li>Work with database team in order to make performance updates (indexes, etc.) and recommend structural changes.</li>
    <li>Deploy to QA, UAT and Production environments and manage all servers from initial configuration onward.</li>
    <li>Develop unified build process and documentation for performing deployments.</li>
</ul>

<h2");

WriteLiteral(" class=\"history-item row\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">11/2008 - Present</span>\r\n        <span");

WriteLiteral(" class=\"col-md-6 text-center\"");

WriteLiteral(">Quantum Concepts Corporation</span>\r\n        <span");

WriteLiteral(" class=\"col-md-3 text-right\"");

WriteLiteral(@">Leesburg, Virginia</span>
    </span>
</h2>
<h3>Owner</h3>
<ul>
    <li>Research, design, develop, test and deploy software for the Windows Phone platform.</li>
    <li>Write applications using the .NET Compact Framework.</li>
    <li>Develop and release custom code generation tool, CodeGenerator (TheCodeGenerator.com) which provides a huge boost to team productivity as well as code stability and versatility.</li>
</ul>

<h2");

WriteLiteral(" class=\"history-item row\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">11/2008 - 11/2009</span>\r\n        <span");

WriteLiteral(" class=\"col-md-6 text-center\"");

WriteLiteral(">Corporate Executive Board</span>\r\n        <span");

WriteLiteral(" class=\"col-md-3 text-right\"");

WriteLiteral(@">Arlington, Virginia</span>
    </span>
</h2>
<h3>Software Consultant</h3>
<ul>
    <li>Full life-cycle design and development for system to generate reports and benchmarks based on survey data.</li>
    <li>Built on ASP.NET 3.5/WebForms, SQL Server 2005/2008, Aspose.Slides (dynamic PPT altering tool), Dundas Charts.</li>
    <li>Survey data consumption, configuration, calculation, and reporting.</li>
    <li>Ability to perform Dynamic Reporting based on user-selected demographic elements.</li>
    <li>Develop web interface wrapper to interact with survey data provider.</li>
</ul>

<h2");

WriteLiteral(" class=\"history-item row\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">2/2005 - 4/2010</span>\r\n        <span");

WriteLiteral(" class=\"col-md-6 text-center\"");

WriteLiteral(">Avenity, Inc.</span>\r\n        <span");

WriteLiteral(" class=\"col-md-3 text-right\"");

WriteLiteral(">Reston, Virginia</span>\r\n    </span>\r\n</h2>\r\n<h3>Senior Software Developer</h3>\r" +
"\n<ul>\r\n    <li>\r\n        Local Government Revenue Management System,  .NET Frame" +
"work:\r\n        <ul>\r\n            <li>Design, develop, and unit test complex clie" +
"nt/server software supplications using both .NET Remoting and Web Services API l" +
"ayers.</li>\r\n            <li>Utilize and improve a custom code generator to gene" +
"rate data objects and API layers.</li>\r\n            <li>Implement customizations" +
" in external DLLs for each client.</li>\r\n            <li>Create and enhance SQL " +
"Server Reporting Services reports as well as develop Custom (ad-hoc) Reporting e" +
"ngine.</li>\r\n            <li>Lead developer for related public-facing web site.<" +
"/li>\r\n            <li>Design and implement workflow/processing queue.</li>\r\n    " +
"        <li>Performance and memory optimization throughout enterprise-level soft" +
"ware package.</li>\r\n        </ul>\r\n    </li>\r\n    <li>\r\n        Compensation Ana" +
"lysis System, J2EE & Weblogic:\r\n        <ul>\r\n            <li>Develop complex we" +
"b application and Windows services using Java/J2EE platform.</li>\r\n            <" +
"li>Create and refine complex SQL queries, stored procedures and views on Oracle " +
"platform.</li>\r\n            <li>Lead developer on multiple software iterations.<" +
"/li>\r\n        </ul>\r\n    </li>\r\n    <li>\r\n        General:\r\n        <ul>\r\n      " +
"      <li>Go-to-guy for network and server configuration; implemented custom VOI" +
"P solution (Asterisk); developed in-house time-tracking system; presented softwa" +
"re development training courses to other employees; excellent evaluations each y" +
"ear.</li>\r\n        </ul>\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
