#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Education
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using JSM.Web.Models.Shared;
    using JSM.Web.Models.Shared.Resume;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Education/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Education\Index.cshtml"
  
    ViewBag.Title = "education";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Views\Education\Index.cshtml"
Write(Html.DisplayForModel());

            
            #line default
            #line hidden
WriteLiteral(@"

<!--
<h2 class=""history-item"">
    <span class=""row"">
        <span class=""col-md-3"">8/2000 - 12/2004</span>
        <span class=""col-md-6 text-center"">Champlain College</span>
        <span class=""col-md-3 text-right"">Burlington, Vermont</span>
    </span>
</h2>
<ul>
    <li>Received a Bachelor Degree in Software Engineering in December 2004.</li>
    <li>Received an Associate Degree in Software Development in December 2003.</li>
    <li>Software-related courses focused on hands-on skills in addition to theory.</li>
    <li>Selected to be a tutor in the Programming Lab.</li>
</ul>
-->");

        }
    }
}
#pragma warning restore 1591
