#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.ContactMe
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using JSM.Web.Models.Shared;
    using JSM.Web.Models.Shared.Resume;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ContactMe/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ContactMe\Index.cshtml"
  
    ViewBag.Title = "contact me";
    ViewBag.PageTitle = ViewBag.Title;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<p>If you\'d like to get in touch with me, please use one of the following met" +
"hods:</p>\r\n\r\n");

            
            #line 8 "..\..\Views\ContactMe\Index.cshtml"
  Html.RenderPartial("_InfoSlider", new InfoSliderModel() {
    Id = "emailSlider",
    Label = "email"
});
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Views\ContactMe\Index.cshtml"
  Html.RenderPartial("_InfoSlider", new InfoSliderModel() {
      Id = "phoneSlider",
      Label = "phone"
});
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Head", () => {

WriteLiteral("\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 467), Tuple.Create("\"", 526)
            
            #line 19 "..\..\Views\ContactMe\Index.cshtml"
, Tuple.Create(Tuple.Create("", 474), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Stylesheets/InfoSlider.css")
            
            #line default
            #line hidden
, 474), false)
);

WriteLiteral("/>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 590), Tuple.Create("\"", 643)
            
            #line 23 "..\..\Views\ContactMe\Index.cshtml"
, Tuple.Create(Tuple.Create("", 596), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Scripts/InfoSlider.js")
            
            #line default
            #line hidden
, 596), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            var $emailSlider = $(\"#em" +
"ailSlider\");\r\n            var $phoneSlider = $(\"#phoneSlider\");\r\n\r\n            $" +
"emailSlider.infoSlider(sliderCallback.bind($emailSlider, \"");

            
            #line 29 "..\..\Views\ContactMe\Index.cshtml"
                                                                  Write(Url.Action("GetEmail"));

            
            #line default
            #line hidden
WriteLiteral("\", function (data) {\r\n                return $(\"<a>\")\r\n                    .text(" +
"data)\r\n                    .attr(\"href\", \"mailto:\" + data);\r\n            }));\r\n " +
"           $phoneSlider.infoSlider(sliderCallback.bind($phoneSlider, \"");

            
            #line 34 "..\..\Views\ContactMe\Index.cshtml"
                                                                  Write(Url.Action("GetPhone"));

            
            #line default
            #line hidden
WriteLiteral(@"""));
        });

        function sliderCallback(url, contentCallback) {
            var $sliderElement = this;

            $.post(url, function (data) {
                var infoSlider = $sliderElement.getInfoSlider();

                infoSlider.onSliding = null;
                infoSlider.setContent(contentCallback instanceof Function ? contentCallback(data) : data);
            });
        }
</script>
");

});

        }
    }
}
#pragma warning restore 1591
