#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ContactMe/Index.cshtml")]
    public partial class _Views_ContactMe_Index_cshtml : System.Web.Mvc.WebViewPage<JSM.Web.Models.ContactMe.SendMessageModel>
    {
        public _Views_ContactMe_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\ContactMe\Index.cshtml"
  
    ViewBag.Title = "contact me";
    ViewBag.PageTitle = ViewBag.Title;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\ContactMe\Index.cshtml"
  Html.RenderPartial("_ContactInfo");
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Views\ContactMe\Index.cshtml"
 using (Html.BeginForm("Index", "ContactMe", FormMethod.Post)) {

            
            #line default
            #line hidden
WriteLiteral("    <p>Or you can send me a message right now...</p>\r\n");

            
            #line 12 "..\..\Views\ContactMe\Index.cshtml"

    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\ContactMe\Index.cshtml"
                                
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.EditorFor(m => m.Email));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\ContactMe\Index.cshtml"
                                 

    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.LabelFor(m => m.Subject));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\ContactMe\Index.cshtml"
                                  
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.EditorFor(m => m.Subject));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\ContactMe\Index.cshtml"
                                   

    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.LabelFor(m => m.Message));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\ContactMe\Index.cshtml"
                                  
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.EditorFor(m => m.Message));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\ContactMe\Index.cshtml"
                                   
    
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\ContactMe\Index.cshtml"
Write(Html.EditorFor(m => m.SecurityQuestion));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\ContactMe\Index.cshtml"
                                            
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"footer\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-check\"");

WriteLiteral("></span> Send Message</button>\r\n    </div>\r\n");

            
            #line 27 "..\..\Views\ContactMe\Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
