#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ContactMe/Thanks.cshtml")]
    public partial class _Views_ContactMe_Thanks_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ContactMe_Thanks_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ContactMe\Thanks.cshtml"
  
    ViewBag.Title = "message received";
    ViewBag.PageTitle = ViewBag.Title;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<p");

WriteLiteral(" class=\"success\"");

WriteLiteral(">Thanks for your message, I\'ll get back to you as soon as I can.</p>");

        }
    }
}
#pragma warning restore 1591
