#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using JSM.Web.Models.Shared;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_InfoSlider.cshtml")]
    public partial class InfoSlider : System.Web.Mvc.WebViewPage<InfoSliderModel>
    {
        public InfoSlider()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteAttribute("id", Tuple.Create(" id=\"", 30), Tuple.Create("\"", 44)
            
            #line 3 "..\..\Views\Shared\_InfoSlider.cshtml"
, Tuple.Create(Tuple.Create("", 35), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 35), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 45), Tuple.Create("\"", 87)
            
            #line 3 "..\..\Views\Shared\_InfoSlider.cshtml"
, Tuple.Create(Tuple.Create("", 53), Tuple.Create<System.Object, System.Int32>(Model.CssClass ?? "info-slider"
            
            #line default
            #line hidden
, 53), false)
);

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">");

            
            #line 4 "..\..\Views\Shared\_InfoSlider.cshtml"
                   Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <span");

WriteLiteral(" class=\"content\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Shared\_InfoSlider.cshtml"
                      Write(new MvcHtmlString(Model.Content));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <span");

WriteLiteral(" class=\"slider\"");

WriteLiteral("><span");

WriteLiteral(" class=\"grip\"");

WriteLiteral("></span><span");

WriteLiteral(" class=\"hint\"");

WriteLiteral(">");

            
            #line 6 "..\..\Views\Shared\_InfoSlider.cshtml"
                                                                  Write(Model.Hint ?? "> slide to reveal");

            
            #line default
            #line hidden
WriteLiteral("</span></span>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
