#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSM.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using JSM.Web;
    using QuantumConcepts.Common.Extensions;
    using QuantumConcepts.Common.Mvc.Extensions;
    using QuantumConcepts.Common.Mvc.Utils;
    using QuantumConcepts.Common.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"Josh McCullough\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"I\'m a highly skilled software engineer who prides himself on completing" +
" tasks on time while maintaining high quality standards and adhering to software" +
" development best practices.\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(" content=\"software,development,engineering,engineer,c#,.NET,coding,coder,for hire" +
"\"");

WriteLiteral("/>\r\n        <title>Josh McCullough | A top-quality, full-stack software engineer." +
"</title>\r\n        <link");

WriteLiteral(" href=\"http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400itali" +
"c,700italic\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral("/>\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
   Write(Styles.Render("~/Content/Stylesheets/3rdParty"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
   Write(Styles.Render("~/Content/Stylesheets/Site"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
   Write(Scripts.Render("~/Content/Scripts/3rdParty"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
   Write(Scripts.Render("~/Content/Scripts/Site"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderSection("Head", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n    <body");

WriteAttribute("class", Tuple.Create(" class=\"", 1065), Tuple.Create("\"", 1178)
, Tuple.Create(Tuple.Create("", 1073), Tuple.Create("Controller-", 1073), true)
            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1084), Tuple.Create<System.Object, System.Int32>(ViewContext.RouteData.Values["controller"]
            
            #line default
            #line hidden
, 1084), false)
, Tuple.Create(Tuple.Create(" ", 1129), Tuple.Create("Action-", 1130), true)
            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
  , Tuple.Create(Tuple.Create("", 1137), Tuple.Create<System.Object, System.Int32>(ViewContext.RouteData.Values["action"]
            
            #line default
            #line hidden
, 1137), false)
);

WriteLiteral(">\r\n        <header>\r\n            <div");

WriteLiteral(" class=\"row About\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-12 col-md-3 Name\"");

WriteLiteral(">Josh McCullough</div>\r\n                <ul");

WriteLiteral(" class=\"col-xs-12 col-md-9 Roles\"");

WriteLiteral(@">
                    <li>software engineer</li>
                    <li>leader</li>
                    <li>database developer</li>
                    <li>mentor</li>
                    <li>ui/ux designer</li>
                </ul>
            </div>
            <nav");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 30 "..\..\Views\Shared\_Layout.cshtml"
           Write(NavUtil.WriteMenuLink(Html, "overview", "Index", "Overview", null, "Overview"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
           Write(NavUtil.WriteMenuLink(Html, "skills & tech", "Index", "SkillsAndTech", null, "SkillsAndTech"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
           Write(NavUtil.WriteMenuLink(Html, "work history", "Index", "WorkHistory", null, "WorkHistory"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
           Write(NavUtil.WriteMenuLink(Html, "education", "Index", "Education", null, "Education"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
           Write(NavUtil.WriteMenuLink(Html, "contact me", "Index", "ContactMe", null, "ContactMe"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </nav>\r\n        </header>\r\n\r\n        <section");

WriteLiteral(" id=\"Content\"");

WriteLiteral(">\r\n            <div>\r\n                <h1><span>");

            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
                     Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></h1>\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </section>\r\n\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
   Write(Scripts.Render("~/Content/Scripts/3rdParty"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
   Write(Scripts.Render("~/Content/Scripts/Site"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderSection("Scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
